guardian signature
boklisten/bl-email pull request #5
Opened 2024-04-10 17:58 UTC by AdrianAndersen

- **feat: guardian signature emails**
- **build: add .nvmrc**
- **1.7.3**
- **feat: add email template for guardian signature**
- **1.7.4**

2024-04-10 18:00 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Legge til rutine for utsending av epost + SMS med lenke til signering for foresatte](https://trello.com/c/hLCSEFZE/903-legge-til-rutine-for-utsending-av-epost-sms-med-lenke-til-signering-for-foresatte)

2024-04-10 18:03 UTC, AdrianAndersen commented
See https://github.com/boklisten/bl-api/pull/496

2024-04-17 15:22 UTC, LarsSelbekk requested changes

2024-04-17 15:22 UTC, LarsSelbekk commented on src/pages/guardian-signature.html
> +        Boklisten.no. Ettersom {{i 'emailTemplateInput.userFullName'}} er under
Branch name

2024-04-30 17:52 UTC, LarsSelbekk requested changes

2024-04-30 17:52 UTC, LarsSelbekk commented on src/pages/guardian-signature.html
> +        Boklisten.no {{i 'emailTemplateInput.extra.branchName'}}. Ettersom {{i
I would prefer a little more fancy formatting, e.g. "bestilt bøker fra Ullern VGS gjennom Boklisten.no", and if branch not set, "bestilt bøker fra Boklisten.no". The way you currently have it, there will be an extra space in front of the period if the branch name is not set.

2024-05-08 13:29 UTC, LarsSelbekk approved these changes

2024-05-08 13:30 UTC, merged